enum ActionType {
  SET_USER_SUCCESS = 'SET_USER_SUCCESS',
  SET_USER_FAILURE = 'SET_USER_FAILURE',
  CLEAR_SET_USER_ERROR = 'CLEAR_SET_USER_ERROR',

  SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS',
  SAVE_USER_FAILURE = 'SAVE_USER_FAILURE',
  CLEAR_SAVE_USER_ERROR = 'CLEAR_SAVE_USER_ERROR',

  SET_USER_DISPLAY_NAME = 'SET_USER_DISPLAY_NAME',
  SET_USER_AVATAR = 'SET_USER_AVATAR',
  SET_USER_THEME = 'SET_USER_THEME',
  SET_USER_BUDGET = 'SET_USER_BUDGET',
}

export default ActionType;
