enum ActionType {
  SAVE_BILL_SUCCESS = 'SAVE_BILL_SUCCESS',
  SAVE_BILL_FAILURE = 'SAVE_BILL_FAILURE',
  CLEAR_SAVE_BILL_ERROR = 'CLEAR_SAVE_BILL_ERROR',

  FETCH_BILLS_SUCCESS = 'FETCH_BILLS_SUCCESS',
  FETCH_BILLS_FAILURE = 'FETCH_BILLS_FAILURE',
  CLEAR_FETCH_BILLS_ERROR = 'CLEAR_FETCH_BILLS_ERROR',
}

export default ActionType;
