enum ActionType {
  SAVE_EXPENSE_SUCCESS = 'SAVE_EXPENSE_SUCCESS',
  SAVE_EXPENSE_FAILURE = 'SAVE_EXPENSE_FAILURE',
  CLEAR_SAVE_EXPENSE_ERROR = 'CLEAR_SAVE_EXPENSE_ERROR',

  FETCH_EXPENSES_BY_MONTH_SUCCESS = 'FETCH_EXPENSES_BY_MONTH_SUCCESS',
  FETCH_EXPENSES_BY_MONTH_FAILURE = 'FETCH_EXPENSES_BY_MONTH_FAILURE',
  CLEAR_FETCH_EXPENSES_BY_MONTH_ERROR = 'CLEAR_FETCH_EXPENSES_BY_MONTH_ERROR',

  FETCH_EXPENSE_SUCCESS = 'FETCH_EXPENSE_SUCCESS',
  FETCH_EXPENSE_FAILURE = 'FETCH_EXPENSE_FAILURE',
  CLEAR_FETCH_EXPENSE_ERROR = 'CLEAR_FETCH_EXPENSE_ERROR',

  SET_MONTH = 'SET_MONTH',
  SET_YEAR = 'SET_YEAR',
}

export default ActionType;
