enum ActionType {
  TOGGLE_AUTHENTICATING = 'TOGGLE_AUTHENTICATING',
  TOGGLE_LOADING = 'TOGGLE_LOADING',
  TOGGLE_SIDE_DRAWER_OPEN = 'TOGGLE_SIDE_DRAWER_OPEN',
  TOGGLE_SAVING = 'TOGGLE_SAVING',
}

export default ActionType;
